export const GET_LIST_STARTED = "GET_LIST_STARTED"
export const GET_LIST = "GET_LIST"
export const CREATE_TODO = "CREATE_TODO"
export const DELETE_TODO = "DELETE_TODO"
export const EDIT_TODO = "EDIT_TODO"
export const GET_EDIT_ITEM = "GET_EDIT_ITEM"
export const SEARCH_TODO = "SEARCH_TODO"